### ISSUE TITLE
React Three Drei OrbitControls einbauen // Attribute etc.

### ISSUE THREAD

**Issue by Naasgul** [Naasgul/visual-experience#2]

**Comment by maaaaaaaaaaaaaaaax** [comment]
Die folgenden attribute sind verfügbar:

enableDamping, enableZoom, enableRotate, enablePan, enabled 

Zudem können bestimmte kameras/ object hinzugefügt werden um, oder mit denen sich dann bewegt wird. 

Für uns ist das erst einmal uninteressant.
